export const countries = [
  { name: "Afghanistan", code: "AF", currency: "Afghani", symbol: "؋" },
  { name: "Albania", code: "AL", currency: "Lek", symbol: "Lek" },
  { name: "Algeria", code: "DZ", currency: "Dinar", symbol: "دج" },
  { name: "Andorra", code: "AD", currency: "Euro", symbol: "€" },
  { name: "Angola", code: "AO", currency: "Kwanza", symbol: "Kz" },
  { name: "Antigua and Barbuda", code: "AG", currency: "East Caribbean Dollar", symbol: "$" },
  { name: "Argentina", code: "AR", currency: "Peso", symbol: "$" },
  { name: "Armenia", code: "AM", currency: "Dram", symbol: "֏" },
  { name: "Australia", code: "AU", currency: "Dollar", symbol: "$" },
  { name: "Austria", code: "AT", currency: "Euro", symbol: "€" },
  { name: "Azerbaijan", code: "AZ", currency: "Manat", symbol: "₼" },
  { name: "Bahamas", code: "BS", currency: "Dollar", symbol: "$" },
  { name: "Bahrain", code: "BH", currency: "Dinar", symbol: "دج" },
  { name: "Bangladesh", code: "BD", currency: "Taka", symbol: "৳" },
  { name: "Barbados", code: "BB", currency: "Dollar", symbol: "$" },
  { name: "Belarus", code: "BY", currency: "Ruble", symbol: "р." },
  { name: "Belgium", code: "BE", currency: "Euro", symbol: "€" },
  { name: "Belize", code: "BZ", currency: "Dollar", symbol: "$" },
  { name: "Benin", code: "BJ", currency: "CFA franc", symbol: "₣" },
  { name: "Bhutan", code: "BT", currency: "Ngultrum", symbol: "Nu." },
  { name: "Bolivia", code: "BO", currency: "Boliviano", symbol: "Bs." },
  { name: "Bosnia and Herzegovina", code: "BA", currency: "Marka", symbol: "KM" },
  { name: "Botswana", code: "BW", currency: "Pula", symbol: "P" },
  { name: "Brazil", code: "BR", currency: "Real", symbol: "R$" },
  { name: "Brunei", code: "BN", currency: "Dollar", symbol: "$" },
  { name: "Bulgaria", code: "BG", currency: "Lev", symbol: "лв." },
  { name: "Burkina Faso", code: "BF", currency: "CFA franc", symbol: "₣" },
  { name: "Burundi", code: "BI", currency: "Franc", symbol: "₣" },
  { name: "Cabo Verde", code: "CV", currency: "Cabo Verde escudo", symbol: "Esc" },
  { name: "Cambodia", code: "KH", currency: "Riel", symbol: "៛" },
  { name: "Cameroon", code: "CM", currency: "CFA franc", symbol: "₣" },
  { name: "Canada", code: "CA", currency: "Dollar", symbol: "$" },
  { name: "Central African Republic", code: "CF", currency: "CFA franc", symbol: "₣" },
  { name: "Chad", code: "TD", currency: "Franc", symbol: "₣" },
  { name: "Chile", code: "CL", currency: "Peso", symbol: "$" },
  { name: "China", code: "CN", currency: "Yuan", symbol: "¥" },
  { name: "Colombia", code: "CO", currency: "Peso", symbol: "$" },
  { name: "Comoros", code: "KM", currency: "Franc", symbol: "₣" },
  { name: "Congo (Congo-Brazzaville)", code: "CG", currency: "Franc", symbol: "₣" },
  { name: "Congo (Congo-Kinshasa)", code: "CD", currency: "Franc", symbol: "₣" },
  { name: "Costa Rica", code: "CR", currency: "Colón", symbol: "₡" },
  { name: "Croatia", code: "HR", currency: "Kuna", symbol: "kn" },
  { name: "Cuba", code: "CU", currency: "Peso", symbol: "$" },
  { name: "Cyprus", code: "CY", currency: "Euro", symbol: "€" },
  { name: "Czechia", code: "CZ", currency: "Koruna", symbol: "Kč" },
  { name: "Denmark", code: "DK", currency: "Krone", symbol: "kr" },
  { name: "Djibouti", code: "DJ", currency: "Franc", symbol: "₣" },
  { name: "Dominica", code: "DM", currency: "Dollar", symbol: "$" },
  { name: "Dominican Republic", code: "DO", currency: "Peso", symbol: "$" },
  { name: "Ecuador", code: "EC", currency: "Dollar", symbol: "$" },
  { name: "Egypt", code: "EG", currency: "Pound", symbol: "£" },
  { name: "El Salvador", code: "SV", currency: "Dollar", symbol: "$" },
  { name: "Equatorial Guinea", code: "GQ", currency: "Franc", symbol: "₣" },
  { name: "Eritrea", code: "ER", currency: "Nakfa", symbol: "Nfk" },
  { name: "Estonia", code: "EE", currency: "Euro", symbol: "€" },
  { name: "Eswatini", code: "SZ", currency: "Lilangeni", symbol: "L" },
  { name: "Ethiopia", code: "ET", currency: "Ethiopian birr", symbol: "Br" },
  { name: "Fiji", code: "FJ", currency: "Dollar", symbol: "$" },
  { name: "Finland", code: "FI", currency: "Euro", symbol: "€" },
  { name: "France", code: "FR", currency: "Euro", symbol: "€" },
  { name: "Gabon", code: "GA", currency: "Franc", symbol: "₣" },
  { name: "Gambia", code: "GM", currency: "Dalasi", symbol: "D" },
  { name: "Georgia", code: "GE", currency: "Lari", symbol: "₾" },
  { name: "Germany", code: "DE", currency: "Euro", symbol: "€" },
  { name: "Ghana", code: "GH", currency: "Cedi", symbol: "₵" },
  { name: "Greece", code: "GR", currency: "Euro", symbol: "€" },
  { name: "Grenada", code: "GD", currency: "Dollar", symbol: "$" },
  { name: "Guatemala", code: "GT", currency: "Quetzal", symbol: "Q" },
  { name: "Guinea", code: "GN", currency: "Franc", symbol: "₣" },
  { name: "Guinea-Bissau", code: "GW", currency: "Franc", symbol: "₣" },
  { name: "Guyana", code: "GY", currency: "Dollar", symbol: "$" },
  { name: "Haiti", code: "HT", currency: "Gourde", symbol: "G" },
  { name: "Honduras", code: "HN", currency: "Lempira", symbol: "L" },
  { name: "Hungary", code: "HU", currency: "Forint", symbol: "Ft" },
  { name: "Iceland", code: "IS", currency: "Krona", symbol: "kr" },
  { name: "India", code: "IN", currency: "Rupee", symbol: "₹" },
  { name: "Indonesia", code: "ID", currency: "Rupiah", symbol: "Rp" },
  { name: "Iran", code: "IR", currency: "Rial", symbol: "ریال" },
  { name: "Iraq", code: "IQ", currency: "Dinar", symbol: "ع.د" },
  { name: "Ireland", code: "IE", currency: "Euro", symbol: "€" },
  { name: "Israel", code: "IL", currency: "Shekel", symbol: "₪" },
  { name: "Italy", code: "IT", currency: "Euro", symbol: "€" },
  { name: "Jamaica", code: "JM", currency: "Dollar", symbol: "$" },
  { name: "Japan", code: "JP", currency: "Yen", symbol: "¥" },
  { name: "Jordan", code: "JO", currency: "Dinar", symbol: "د.ا" },
  { name: "Kazakhstan", code: "KZ", currency: "Tenge", symbol: "₸" },
  { name: "Kenya", code: "KE", currency: "Shilling", symbol: "Sh" },
  { name: "Kiribati", code: "KI", currency: "Dollar", symbol: "$" },
  { name: "Kuwait", code: "KW", currency: "Dinar", symbol: "د.ك" },
  { name: "Kyrgyzstan", code: "KG", currency: "Som", symbol: "с" },
  { name: "Laos", code: "LA", currency: "Kip", symbol: "₭" },
  { name: "Latvia", code: "LV", currency: "Euro", symbol: "€" },
  { name: "Lebanon", code: "LB", currency: "Pound", symbol: "£" },
  { name: "Lesotho", code: "LS", currency: "Rand", symbol: "R" },
  { name: "Liberia", code: "LR", currency: "Dollar", symbol: "$" },
  { name: "Libya", code: "LY", currency: "Dinar", symbol: "ل.د" },
  { name: "Liechtenstein", code: "LI", currency: "Swiss Franc", symbol: "CHF" },
  { name: "Lithuania", code: "LT", currency: "Euro", symbol: "€" },
  { name: "Luxembourg", code: "LU", currency: "Euro", symbol: "€" },
  { name: "Madagascar", code: "MG", currency: "Franc", symbol: "Ar" },
  { name: "Malawi", code: "MW", currency: "Kwacha", symbol: "MK" },
  { name: "Malaysia", code: "MY", currency: "Ringgit", symbol: "RM" },
  { name: "Maldives", code: "MV", currency: "Rufiyaa", symbol: "MVR" },
  { name: "Mali", code: "ML", currency: "Franc", symbol: "CFA" },
  { name: "Malta", code: "MT", currency: "Euro", symbol: "€" },
  { name: "Mauritania", code: "MR", currency: "Ouguiya", symbol: "MRU" },
  { name: "Mauritius", code: "MU", currency: "Rupee", symbol: "Rs" },
  { name: "Mexico", code: "MX", currency: "Peso", symbol: "$" },
  { name: "Moldova", code: "MD", currency: "Leu", symbol: "MDL" },
  { name: "Monaco", code: "MC", currency: "Euro", symbol: "€" },
  { name: "Mongolia", code: "MN", currency: "Tugrik", symbol: "₮" },
  { name: "Montenegro", code: "ME", currency: "Euro", symbol: "€" },
  { name: "Morocco", code: "MA", currency: "Dirham", symbol: "د.م." },
  { name: "Mozambique", code: "MZ", currency: "Metical", symbol: "MT" },
  { name: "Myanmar", code: "MM", currency: "Kyat", symbol: "Ks" },
  { name: "Namibia", code: "NA", currency: "Rand", symbol: "R" },
  { name: "Nepal", code: "NP", currency: "Rupee", symbol: "Rs" },
  { name: "Netherlands", code: "NL", currency: "Euro", symbol: "€" },
  { name: "New Zealand", code: "NZ", currency: "Dollar", symbol: "$" },
  { name: "Nicaragua", code: "NI", currency: "Cordoba", symbol: "C$" },
  { name: "Niger", code: "NE", currency: "Franc", symbol: "₣" },
  { name: "Nigeria", code: "NG", currency: "Naira", symbol: "₦" },
  { name: "North Macedonia", code: "MK", currency: "Denar", symbol: "ден" },
  { name: "Norway", code: "NO", currency: "Norwegian Krone", symbol: "kr" },
  { name: "Oman", code: "OM", currency: "Rial", symbol: "ریال" },
  { name: "Pakistan", code: "PK", currency: "Rupee", symbol: "Rs" },
  { name: "Panama", code: "PA", currency: "Balboa", symbol: "B/." },
  { name: "Paraguay", code: "PY", currency: "Guarani", symbol: "₲" },
  { name: "Peru", code: "PE", currency: "Sol", symbol: "S/." },
  { name: "Philippines", code: "PH", currency: "Peso", symbol: "₱" },
  { name: "Poland", code: "PL", currency: "Zloty", symbol: "zł" },
  { name: "Portugal", code: "PT", currency: "Euro", symbol: "€" },
  { name: "Russia", code: "RU", currency: "Russian Ruble", symbol: "₽" },
  { name: "Spain", code: "ES", currency: "Euro", symbol: "€" },
  { name: "United Kingdom", code: "GB", currency: "Pound Sterling", symbol: "£" },
  { name: "United States", code: "US", currency: "Dollar", symbol: "$" }
] as const;

