


export const currencies = [
    { name: "Afghan Afghani", code: "AFN", symbol: "؋" },
    { name: "Albanian Lek", code: "ALL", symbol: "L" },
    { name: "Algerian Dinar", code: "DZD", symbol: "د.ج" },
    { name: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
    { name: "Argentine Peso", code: "ARS", symbol: "$" },
    { name: "Armenian Dram", code: "AMD", symbol: "֏" },
    { name: "Australian Dollar", code: "AUD", symbol: "$" },
    { name: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
    { name: "Bahamian Dollar", code: "BSD", symbol: "$" },
    { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
    { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
    { name: "Barbadian Dollar", code: "BBD", symbol: "$" },
    { name: "Belarusian Ruble", code: "BYN", symbol: "Br" },
    { name: "Belize Dollar", code: "BZD", symbol: "$" },
    { name: "Bermudian Dollar", code: "BMD", symbol: "$" },
    { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
    { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs." },
    { name: "Brazilian Real", code: "BRL", symbol: "R$" },
    { name: "British Pound", code: "GBP", symbol: "£" },
    { name: "Brunei Dollar", code: "BND", symbol: "$" },
    { name: "Bulgarian Lev", code: "BGN", symbol: "лв" },
    { name: "Burundian Franc", code: "BIF", symbol: "FBu" },
    { name: "Cambodian Riel", code: "KHR", symbol: "៛" },
    { name: "Canadian Dollar", code: "CAD", symbol: "$" },
    { name: "Chilean Peso", code: "CLP", symbol: "$" },
    { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
    { name: "Colombian Peso", code: "COP", symbol: "$" },
    { name: "Costa Rican Colón", code: "CRC", symbol: "₡" },
    { name: "Croatian Kuna", code: "HRK", symbol: "kn" },
    { name: "Cuban Peso", code: "CUP", symbol: "$" },
    { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
    { name: "Danish Krone", code: "DKK", symbol: "kr" },
    { name: "Djiboutian Franc", code: "DJF", symbol: "Fdj" },
    { name: "Dominican Peso", code: "DOP", symbol: "$" },
    { name: "Egyptian Pound", code: "EGP", symbol: "£" },
    { name: "Euro", code: "EUR", symbol: "€" },
    { name: "Fijian Dollar", code: "FJD", symbol: "$" },
    { name: "Gambian Dalasi", code: "GMD", symbol: "D" },
    { name: "Georgian Lari", code: "GEL", symbol: "₾" },
    { name: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
    { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
    { name: "Haitian Gourde", code: "HTG", symbol: "G" },
    { name: "Honduran Lempira", code: "HNL", symbol: "L" },
    { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
    { name: "Icelandic Króna", code: "ISK", symbol: "kr" },
    { name: "Indian Rupee", code: "INR", symbol: "₹" },
    { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
    { name: "Iranian Rial", code: "IRR", symbol: "﷼" },
    { name: "Iraqi Dinar", code: "IQD", symbol: "ع.د" },
    { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
    { name: "Jamaican Dollar", code: "JMD", symbol: "$" },
    { name: "Japanese Yen", code: "JPY", symbol: "¥" },
    { name: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
    { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
    { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
    { name: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
    { name: "Kyrgyzstani Som", code: "KGS", symbol: "с" },
    { name: "Lao Kip", code: "LAK", symbol: "₭" },
    { name: "Lebanese Pound", code: "LBP", symbol: "ل.ل" },
    { name: "Lesotho Loti", code: "LSL", symbol: "L" },
    { name: "Liberian Dollar", code: "LRD", symbol: "$" },
    { name: "Libyan Dinar", code: "LYD", symbol: "ل.د" },
    { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
    { name: "Mauritian Rupee", code: "MUR", symbol: "₨" },
    { name: "Mexican Peso", code: "MXN", symbol: "$" },
    { name: "Moldovan Leu", code: "MDL", symbol: "L" },
    { name: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
    { name: "Myanmar Kyat", code: "MMK", symbol: "K" },
    { name: "Namibian Dollar", code: "NAD", symbol: "$" },
    { name: "Nepalese Rupee", code: "NPR", symbol: "₨" },
    { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
    { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
    { name: "Pakistani Rupee", code: "PKR", symbol: "₨" },
    { name: "Panamanian Balboa", code: "PAB", symbol: "B/." },
    { name: "Paraguayan Guarani", code: "PYG", symbol: "₲" },
    { name: "Peruvian Sol", code: "PEN", symbol: "S/." },
    { name: "Philippine Peso", code: "PHP", symbol: "₱" },
    { name: "Polish Złoty", code: "PLN", symbol: "zł" },
    { name: "Russian Ruble", code: "RUB", symbol: "₽" },
    { name: "South African Rand", code: "ZAR", symbol: "R" },
    { name: "Swedish Krona", code: "SEK", symbol: "kr" },
    { name: "Swiss Franc", code: "CHF", symbol: "Fr" },
    { name: "Turkish Lira", code: "TRY", symbol: "₺" },
    { name: "United States Dollar", code: "USD", symbol: "$" }
  ] as const;
  